/*
 * JParker REST API
 * An Open API for parking lot management
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@arielouziel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.aouziel.jparker.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Details about hour rate plus fixed amount pricing policy
 */
@ApiModel(description = "Details about hour rate plus fixed amount pricing policy")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-11T20:35:36.218+02:00[Europe/Paris]")
public class HourRatePlusFixedPricingPolicy extends PricingPolicy {
  public static final String SERIALIZED_NAME_CURRENCY_CODE = "currencyCode";
  @SerializedName(SERIALIZED_NAME_CURRENCY_CODE)
  private String currencyCode;

  public static final String SERIALIZED_NAME_FIXED_PRICE = "fixedPrice";
  @SerializedName(SERIALIZED_NAME_FIXED_PRICE)
  private Integer fixedPrice;

  public static final String SERIALIZED_NAME_HOUR_PRICE = "hourPrice";
  @SerializedName(SERIALIZED_NAME_HOUR_PRICE)
  private Integer hourPrice;

  public HourRatePlusFixedPricingPolicy currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Code of of price currency
   * @return currencyCode
  **/
  @ApiModelProperty(value = "Code of of price currency")
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public HourRatePlusFixedPricingPolicy fixedPrice(Integer fixedPrice) {
    this.fixedPrice = fixedPrice;
    return this;
  }

   /**
   * Fixed amount
   * @return fixedPrice
  **/
  @ApiModelProperty(value = "Fixed amount")
  public Integer getFixedPrice() {
    return fixedPrice;
  }

  public void setFixedPrice(Integer fixedPrice) {
    this.fixedPrice = fixedPrice;
  }

  public HourRatePlusFixedPricingPolicy hourPrice(Integer hourPrice) {
    this.hourPrice = hourPrice;
    return this;
  }

   /**
   * Hour price in smallest unit of currency
   * @return hourPrice
  **/
  @ApiModelProperty(value = "Hour price in smallest unit of currency")
  public Integer getHourPrice() {
    return hourPrice;
  }

  public void setHourPrice(Integer hourPrice) {
    this.hourPrice = hourPrice;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HourRatePlusFixedPricingPolicy hourRatePlusFixedPricingPolicy = (HourRatePlusFixedPricingPolicy) o;
    return Objects.equals(this.currencyCode, hourRatePlusFixedPricingPolicy.currencyCode) &&
        Objects.equals(this.fixedPrice, hourRatePlusFixedPricingPolicy.fixedPrice) &&
        Objects.equals(this.hourPrice, hourRatePlusFixedPricingPolicy.hourPrice) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currencyCode, fixedPrice, hourPrice, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HourRatePlusFixedPricingPolicy {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    fixedPrice: ").append(toIndentedString(fixedPrice)).append("\n");
    sb.append("    hourPrice: ").append(toIndentedString(hourPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

