/*
 * JParker REST API
 * An Open API for parking lot management
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@arielouziel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.aouziel.jparker.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.aouziel.jparker.client.model.ParkingSlot;
import com.aouziel.jparker.client.model.PricingPolicy;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * All details about parking lots. 
 */
@ApiModel(description = "All details about parking lots. ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-11T14:00:44.729+02:00[Europe/Brussels]")
public class ParkingLot {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PRICING_POLICY = "pricingPolicy";
  @SerializedName(SERIALIZED_NAME_PRICING_POLICY)
  private PricingPolicy pricingPolicy = null;

  public static final String SERIALIZED_NAME_SLOTS = "slots";
  @SerializedName(SERIALIZED_NAME_SLOTS)
  private List<ParkingSlot> slots = new ArrayList<ParkingSlot>();

  public ParkingLot id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * The database generated parking lot ID
   * @return id
  **/
  @ApiModelProperty(value = "The database generated parking lot ID")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ParkingLot name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the parking lot
   * @return name
  **/
  @ApiModelProperty(value = "The name of the parking lot")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ParkingLot pricingPolicy(PricingPolicy pricingPolicy) {
    this.pricingPolicy = pricingPolicy;
    return this;
  }

   /**
   * Get pricingPolicy
   * @return pricingPolicy
  **/
  @ApiModelProperty(value = "")
  public PricingPolicy getPricingPolicy() {
    return pricingPolicy;
  }

  public void setPricingPolicy(PricingPolicy pricingPolicy) {
    this.pricingPolicy = pricingPolicy;
  }

  public ParkingLot slots(List<ParkingSlot> slots) {
    this.slots = slots;
    return this;
  }

  public ParkingLot addSlotsItem(ParkingSlot slotsItem) {
    if (this.slots == null) {
      this.slots = new ArrayList<ParkingSlot>();
    }
    this.slots.add(slotsItem);
    return this;
  }

   /**
   * All the slots of the parking lot
   * @return slots
  **/
  @ApiModelProperty(value = "All the slots of the parking lot")
  public List<ParkingSlot> getSlots() {
    return slots;
  }

  public void setSlots(List<ParkingSlot> slots) {
    this.slots = slots;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParkingLot parkingLot = (ParkingLot) o;
    return Objects.equals(this.id, parkingLot.id) &&
        Objects.equals(this.name, parkingLot.name) &&
        Objects.equals(this.pricingPolicy, parkingLot.pricingPolicy) &&
        Objects.equals(this.slots, parkingLot.slots);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, pricingPolicy, slots);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParkingLot {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pricingPolicy: ").append(toIndentedString(pricingPolicy)).append("\n");
    sb.append("    slots: ").append(toIndentedString(slots)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

