/*
 * JParker REST API
 * An Open API for parking lot management
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@arielouziel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.aouziel.jparker.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PricingPolicy
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-11T14:00:44.729+02:00[Europe/Brussels]")

public class PricingPolicy {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_PRICING_POLICY_TYPE = "pricingPolicyType";
  @SerializedName(SERIALIZED_NAME_PRICING_POLICY_TYPE)
  private String pricingPolicyType;

  public PricingPolicy() {
    this.pricingPolicyType = this.getClass().getSimpleName();
  }
  public PricingPolicy id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public PricingPolicy pricingPolicyType(String pricingPolicyType) {
    this.pricingPolicyType = pricingPolicyType;
    return this;
  }

   /**
   * Type of pricing policy
   * @return pricingPolicyType
  **/
  @ApiModelProperty(value = "Type of pricing policy")
  public String getPricingPolicyType() {
    return pricingPolicyType;
  }

  public void setPricingPolicyType(String pricingPolicyType) {
    this.pricingPolicyType = pricingPolicyType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PricingPolicy pricingPolicy = (PricingPolicy) o;
    return Objects.equals(this.id, pricingPolicy.id) &&
        Objects.equals(this.pricingPolicyType, pricingPolicy.pricingPolicyType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, pricingPolicyType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PricingPolicy {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    pricingPolicyType: ").append(toIndentedString(pricingPolicyType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

