/*
 * JParker REST API
 * An Open API for parking lot management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@arielouziel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.aouziel.jparker.client.api;

import com.aouziel.jparker.client.invoker.ApiException;
import com.aouziel.jparker.client.model.ParkingLot;
import com.aouziel.jparker.client.model.ParkingSlot;
import com.aouziel.jparker.client.model.ParkingSlotUse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ParkingLotControllerApi
 */
@Ignore
public class ParkingLotControllerApiTest {

    private final ParkingLotControllerApi api = new ParkingLotControllerApi();

    
    /**
     * Put a car in a any free parking slot
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void enterParkingLotUsingPOSTTest() throws ApiException {
        Long lotId = null;
        String body = null;
        ParkingSlotUse response = api.enterParkingLotUsingPOST(lotId, body);

        // TODO: test validations
    }
    
    /**
     * View a list of all parking lots
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllParkingLotsUsingGETTest() throws ApiException {
        List<Object> response = api.getAllParkingLotsUsingGET();

        // TODO: test validations
    }
    
    /**
     * Get a parking lot by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getParkingLotByIdUsingGETTest() throws ApiException {
        Long lotId = null;
        ParkingLot response = api.getParkingLotByIdUsingGET(lotId);

        // TODO: test validations
    }
    
    /**
     * Remove car from parking lot and bill the customer
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void leaveParkingLotUsingPUTTest() throws ApiException {
        Long lotId = null;
        Long useId = null;
        ParkingSlotUse response = api.leaveParkingLotUsingPUT(lotId, useId);

        // TODO: test validations
    }
    
    /**
     * Get a list of free slots in a parking lot
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listFreeParkingSlotsUsingGETTest() throws ApiException {
        Long lotId = null;
        String parkingSlotType = null;
        List<ParkingSlot> response = api.listFreeParkingSlotsUsingGET(lotId, parkingSlotType);

        // TODO: test validations
    }
    
}
