/*
 * JParker REST API
 * An Open API for parking lot management
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@arielouziel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.aouziel.jparker.client.model;

import org.junit.Test;


/**
 * Model tests for HourRatePricingPolicy
 */
public class HourRatePricingPolicyTest {
    private final HourRatePricingPolicy model = new HourRatePricingPolicy();

    /**
     * Model tests for HourRatePricingPolicy
     */
    @Test
    public void testHourRatePricingPolicy() {
        // TODO: test HourRatePricingPolicy
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'pricingPolicyType'
     */
    @Test
    public void pricingPolicyTypeTest() {
        // TODO: test pricingPolicyType
    }

}
